import fs from 'fs'
import path from 'path'

const LOCALES_DIR = 'src/i18n/locales'

// English is the base — used as the structural reference.
// Other languages provide their own translated strings for the same keys.
const REMINDERS_EN = {
  title: 'Reminders',
  subtitle: 'Stay on top of your medications & appointments',
  add: 'Add',
  errorPrefix: 'Error',
  notifBanner: {
    title: 'Allow notifications',
    blocked: 'Notifications blocked — enable in device Settings → Apps → MediInfo',
    prompt: 'Get medicine reminders at exactly the right time',
    allow: 'Allow',
    activeTitle: 'Notifications active',
    activeSub: 'reminders fire at exactly the scheduled time',
  },
  stats: {
    total: 'Total',
    active: 'Active',
    takenToday: 'Taken Today',
  },
  tabs: {
    medicine: 'Medicine',
    appointments: 'Appointments',
  },
  status: {
    active: 'Active',
    expired: 'Expired',
  },
  form: {
    newTitle: 'New Medicine Reminder',
    medicineName: 'Medicine Name',
    medicineNamePlaceholder: 'e.g. Paracetamol',
    dosage: 'Dosage',
    dosagePlaceholder: 'e.g. 500mg',
    reminderTime: 'Reminder Time',
    frequency: 'Frequency',
    startDate: 'Start Date',
    endDate: 'End Date',
    notes: 'Notes',
    notesPlaceholder: 'e.g. Take after meals',
    save: 'Save Reminder',
  },
  frequencies: {
    daily: 'daily',
    twiceDaily: 'twice daily',
    threeTimesDaily: 'three times daily',
    weekly: 'weekly',
    asNeeded: 'as needed',
  },
  empty: {
    title: 'No reminders yet',
    subtitle: 'Click "+ Add" to get started',
  },
  markTaken: 'Mark Taken',
  taken: 'Taken',
  delete: 'Delete',
  appointments: {
    emptyTitle: 'No upcoming appointments',
    emptySubtitle: 'Book a doctor to see reminders here',
    upcoming: 'Upcoming',
    reminderSet: 'Reminder set',
  },
}

// Translations for non-English locales. Each top-level key here mirrors
// REMINDERS_EN's structure exactly.
const TRANSLATIONS = {
  hi: {
    title: 'रिमाइंडर',
    subtitle: 'अपनी दवाओं और अपॉइंटमेंट पर नज़र रखें',
    add: 'जोड़ें',
    errorPrefix: 'त्रुटि',
    notifBanner: {
      title: 'सूचनाएं चालू करें',
      blocked: 'सूचनाएं अवरुद्ध हैं — डिवाइस सेटिंग्स → ऐप्स → MediInfo में चालू करें',
      prompt: 'सही समय पर दवा रिमाइंडर पाएं',
      allow: 'अनुमति दें',
      activeTitle: 'सूचनाएं सक्रिय हैं',
      activeSub: 'रिमाइंडर तय समय पर ही आएंगे',
    },
    stats: { total: 'कुल', active: 'सक्रिय', takenToday: 'आज ली गई' },
    tabs: { medicine: 'दवा', appointments: 'अपॉइंटमेंट' },
    status: { active: 'सक्रिय', expired: 'समाप्त' },
    form: {
      newTitle: 'नई दवा रिमाइंडर',
      medicineName: 'दवा का नाम',
      medicineNamePlaceholder: 'जैसे Paracetamol',
      dosage: 'मात्रा',
      dosagePlaceholder: 'जैसे 500mg',
      reminderTime: 'रिमाइंडर समय',
      frequency: 'आवृत्ति',
      startDate: 'आरंभ तिथि',
      endDate: 'समाप्ति तिथि',
      notes: 'टिप्पणी',
      notesPlaceholder: 'जैसे भोजन के बाद लें',
      save: 'रिमाइंडर सहेजें',
    },
    frequencies: {
      daily: 'रोज़ाना',
      twiceDaily: 'दिन में दो बार',
      threeTimesDaily: 'दिन में तीन बार',
      weekly: 'साप्ताहिक',
      asNeeded: 'आवश्यकता अनुसार',
    },
    empty: { title: 'अभी कोई रिमाइंडर नहीं', subtitle: 'शुरू करने के लिए "+ जोड़ें" दबाएं' },
    markTaken: 'ली गई के रूप में चिह्नित करें',
    taken: 'ली गई',
    delete: 'हटाएं',
    appointments: {
      emptyTitle: 'कोई आने वाली अपॉइंटमेंट नहीं',
      emptySubtitle: 'रिमाइंडर देखने के लिए डॉक्टर बुक करें',
      upcoming: 'आने वाली',
      reminderSet: 'रिमाइंडर सेट है',
    },
  },
  mr: {
    title: 'रिमाइंडर',
    subtitle: 'तुमच्या औषधे आणि अपॉइंटमेंटवर लक्ष ठेवा',
    add: 'जोडा',
    errorPrefix: 'त्रुटी',
    notifBanner: {
      title: 'सूचना सुरू करा',
      blocked: 'सूचना अवरोधित आहेत — डिव्हाइस सेटिंग्ज → अॅप्स → MediInfo मध्ये सुरू करा',
      prompt: 'योग्य वेळी औषध रिमाइंडर मिळवा',
      allow: 'परवानगी द्या',
      activeTitle: 'सूचना सक्रिय आहेत',
      activeSub: 'रिमाइंडर ठरलेल्या वेळीच येतील',
    },
    stats: { total: 'एकूण', active: 'सक्रिय', takenToday: 'आज घेतले' },
    tabs: { medicine: 'औषध', appointments: 'अपॉइंटमेंट' },
    status: { active: 'सक्रिय', expired: 'संपलेले' },
    form: {
      newTitle: 'नवीन औषध रिमाइंडर',
      medicineName: 'औषधाचे नाव',
      medicineNamePlaceholder: 'उदा. Paracetamol',
      dosage: 'मात्रा',
      dosagePlaceholder: 'उदा. 500mg',
      reminderTime: 'रिमाइंडर वेळ',
      frequency: 'वारंवारता',
      startDate: 'सुरुवात तारीख',
      endDate: 'समाप्ती तारीख',
      notes: 'टिपा',
      notesPlaceholder: 'उदा. जेवणानंतर घ्या',
      save: 'रिमाइंडर जतन करा',
    },
    frequencies: {
      daily: 'दररोज',
      twiceDaily: 'दिवसातून दोनदा',
      threeTimesDaily: 'दिवसातून तीनदा',
      weekly: 'साप्ताहिक',
      asNeeded: 'आवश्यकतेनुसार',
    },
    empty: { title: 'अजून रिमाइंडर नाहीत', subtitle: 'सुरू करण्यासाठी "+ जोडा" दाबा' },
    markTaken: 'घेतले म्हणून चिन्हांकित करा',
    taken: 'घेतले',
    delete: 'काढा',
    appointments: {
      emptyTitle: 'कोणतीही आगामी अपॉइंटमेंट नाही',
      emptySubtitle: 'रिमाइंडर पाहण्यासाठी डॉक्टर बुक करा',
      upcoming: 'आगामी',
      reminderSet: 'रिमाइंडर सेट आहे',
    },
  },
  ta: {
    title: 'நினைவூட்டல்கள்',
    subtitle: 'உங்கள் மருந்துகள் மற்றும் அப்பாயிண்ட்மென்ட்களை கண்காணியுங்கள்',
    add: 'சேர்க்க',
    errorPrefix: 'பிழை',
    notifBanner: {
      title: 'அறிவிப்புகளை அனுமதிக்கவும்',
      blocked: 'அறிவிப்புகள் தடுக்கப்பட்டுள்ளன — சாதன அமைப்புகள் → ஆப்ஸ் → MediInfo இல் இயக்கவும்',
      prompt: 'சரியான நேரத்தில் மருந்து நினைவூட்டல்களைப் பெறுங்கள்',
      allow: 'அனுமதி',
      activeTitle: 'அறிவிப்புகள் செயலில் உள்ளன',
      activeSub: 'நினைவூட்டல்கள் நிர்ணயிக்கப்பட்ட நேரத்தில் வரும்',
    },
    stats: { total: 'மொத்தம்', active: 'செயலில்', takenToday: 'இன்று எடுத்தது' },
    tabs: { medicine: 'மருந்து', appointments: 'அப்பாயிண்ட்மென்ட்' },
    status: { active: 'செயலில்', expired: 'காலாவதியானது' },
    form: {
      newTitle: 'புதிய மருந்து நினைவூட்டல்',
      medicineName: 'மருந்தின் பெயர்',
      medicineNamePlaceholder: 'எ.கா. Paracetamol',
      dosage: 'அளவு',
      dosagePlaceholder: 'எ.கா. 500mg',
      reminderTime: 'நினைவூட்டல் நேரம்',
      frequency: 'அதிர்வெண்',
      startDate: 'தொடக்க தேதி',
      endDate: 'முடிவு தேதி',
      notes: 'குறிப்புகள்',
      notesPlaceholder: 'எ.கா. சாப்பிட்ட பிறகு எடுக்கவும்',
      save: 'நினைவூட்டலை சேமிக்கவும்',
    },
    frequencies: {
      daily: 'தினமும்',
      twiceDaily: 'நாளுக்கு இரண்டு முறை',
      threeTimesDaily: 'நாளுக்கு மூன்று முறை',
      weekly: 'வாராந்திர',
      asNeeded: 'தேவைப்படும்போது',
    },
    empty: { title: 'இன்னும் நினைவூட்டல்கள் இல்லை', subtitle: 'தொடங்க "+ சேர்க்க" அழுத்தவும்' },
    markTaken: 'எடுத்தது என குறிக்கவும்',
    taken: 'எடுத்தது',
    delete: 'நீக்கு',
    appointments: {
      emptyTitle: 'வரவிருக்கும் அப்பாயிண்ட்மென்ட் இல்லை',
      emptySubtitle: 'நினைவூட்டல்களைப் பார்க்க மருத்துவரை பதிவு செய்யவும்',
      upcoming: 'வரவிருக்கும்',
      reminderSet: 'நினைவூட்டல் அமைக்கப்பட்டது',
    },
  },
  te: {
    title: 'రిమైండర్‌లు',
    subtitle: 'మీ మందులు మరియు అపాయింట్‌మెంట్‌లపై దృష్టి పెట్టండి',
    add: 'జోడించు',
    errorPrefix: 'లోపం',
    notifBanner: {
      title: 'నోటిఫికేషన్‌లను అనుమతించండి',
      blocked: 'నోటిఫికేషన్‌లు బ్లాక్ చేయబడ్డాయి — డివైస్ సెట్టింగ్‌లు → యాప్‌లు → MediInfo లో ఎనేబుల్ చేయండి',
      prompt: 'సరైన సమయంలో మందుల రిమైండర్‌లు పొందండి',
      allow: 'అనుమతించు',
      activeTitle: 'నోటిఫికేషన్‌లు యాక్టివ్‌గా ఉన్నాయి',
      activeSub: 'రిమైండర్‌లు నిర్ణీత సమయంలోనే వస్తాయి',
    },
    stats: { total: 'మొత్తం', active: 'యాక్టివ్', takenToday: 'ఈరోజు తీసుకున్నది' },
    tabs: { medicine: 'మందు', appointments: 'అపాయింట్‌మెంట్‌లు' },
    status: { active: 'యాక్టివ్', expired: 'గడువు ముగిసింది' },
    form: {
      newTitle: 'కొత్త మందు రిమైండర్',
      medicineName: 'మందు పేరు',
      medicineNamePlaceholder: 'ఉదా. Paracetamol',
      dosage: 'మోతాదు',
      dosagePlaceholder: 'ఉదా. 500mg',
      reminderTime: 'రిమైండర్ సమయం',
      frequency: 'ఫ్రీక్వెన్సీ',
      startDate: 'ప్రారంభ తేదీ',
      endDate: 'ముగింపు తేదీ',
      notes: 'గమనికలు',
      notesPlaceholder: 'ఉదా. భోజనం తర్వాత తీసుకోండి',
      save: 'రిమైండర్ సేవ్ చేయండి',
    },
    frequencies: {
      daily: 'ప్రతిరోజూ',
      twiceDaily: 'రోజుకు రెండుసార్లు',
      threeTimesDaily: 'రోజుకు మూడుసార్లు',
      weekly: 'వారానికి',
      asNeeded: 'అవసరమైనప్పుడు',
    },
    empty: { title: 'ఇంకా రిమైండర్‌లు లేవు', subtitle: 'ప్రారంభించడానికి "+ జోడించు" నొక్కండి' },
    markTaken: 'తీసుకున్నట్లు గుర్తించండి',
    taken: 'తీసుకున్నది',
    delete: 'తొలగించు',
    appointments: {
      emptyTitle: 'రాబోయే అపాయింట్‌మెంట్‌లు లేవు',
      emptySubtitle: 'రిమైండర్‌లను చూడటానికి డాక్టర్‌ను బుక్ చేయండి',
      upcoming: 'రాబోయేది',
      reminderSet: 'రిమైండర్ సెట్ చేయబడింది',
    },
  },
  kn: {
    title: 'ರಿಮೈಂಡರ್‌ಗಳು',
    subtitle: 'ನಿಮ್ಮ ಔಷಧಿಗಳು ಮತ್ತು ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳ ಮೇಲೆ ಗಮನ ಇಡಿ',
    add: 'ಸೇರಿಸಿ',
    errorPrefix: 'ದೋಷ',
    notifBanner: {
      title: 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಅನುಮತಿಸಿ',
      blocked: 'ಅಧಿಸೂಚನೆಗಳು ನಿರ್ಬಂಧಿಸಲ್ಪಟ್ಟಿವೆ — ಡಿವೈಸ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು → ಆಪ್‌ಗಳು → MediInfo ನಲ್ಲಿ ಸಕ್ರಿಯಗೊಳಿಸಿ',
      prompt: 'ಸರಿಯಾದ ಸಮಯದಲ್ಲಿ ಔಷಧಿ ರಿಮೈಂಡರ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ',
      allow: 'ಅನುಮತಿಸಿ',
      activeTitle: 'ಅಧಿಸೂಚನೆಗಳು ಸಕ್ರಿಯವಾಗಿವೆ',
      activeSub: 'ರಿಮೈಂಡರ್‌ಗಳು ನಿಗದಿತ ಸಮಯದಲ್ಲಿಯೇ ಬರುತ್ತವೆ',
    },
    stats: { total: 'ಒಟ್ಟು', active: 'ಸಕ್ರಿಯ', takenToday: 'ಇಂದು ತೆಗೆದುಕೊಂಡದ್ದು' },
    tabs: { medicine: 'ಔಷಧಿ', appointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು' },
    status: { active: 'ಸಕ್ರಿಯ', expired: 'ಮುಗಿದಿದೆ' },
    form: {
      newTitle: 'ಹೊಸ ಔಷಧಿ ರಿಮೈಂಡರ್',
      medicineName: 'ಔಷಧಿಯ ಹೆಸರು',
      medicineNamePlaceholder: 'ಉದಾ. Paracetamol',
      dosage: 'ಪ್ರಮಾಣ',
      dosagePlaceholder: 'ಉದಾ. 500mg',
      reminderTime: 'ರಿಮೈಂಡರ್ ಸಮಯ',
      frequency: 'ಆವರ್ತನ',
      startDate: 'ಪ್ರಾರಂಭ ದಿನಾಂಕ',
      endDate: 'ಅಂತ್ಯ ದಿನಾಂಕ',
      notes: 'ಟಿಪ್ಪಣಿಗಳು',
      notesPlaceholder: 'ಉದಾ. ಊಟದ ನಂತರ ತೆಗೆದುಕೊಳ್ಳಿ',
      save: 'ರಿಮೈಂಡರ್ ಉಳಿಸಿ',
    },
    frequencies: {
      daily: 'ಪ್ರತಿದಿನ',
      twiceDaily: 'ದಿನಕ್ಕೆ ಎರಡು ಬಾರಿ',
      threeTimesDaily: 'ದಿನಕ್ಕೆ ಮೂರು ಬಾರಿ',
      weekly: 'ವಾರಕ್ಕೊಮ್ಮೆ',
      asNeeded: 'ಅಗತ್ಯವಿರುವಾಗ',
    },
    empty: { title: 'ಇನ್ನೂ ರಿಮೈಂಡರ್‌ಗಳಿಲ್ಲ', subtitle: 'ಪ್ರಾರಂಭಿಸಲು "+ ಸೇರಿಸಿ" ಒತ್ತಿರಿ' },
    markTaken: 'ತೆಗೆದುಕೊಂಡಂತೆ ಗುರುತಿಸಿ',
    taken: 'ತೆಗೆದುಕೊಂಡದ್ದು',
    delete: 'ಅಳಿಸಿ',
    appointments: {
      emptyTitle: 'ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ',
      emptySubtitle: 'ರಿಮೈಂಡರ್‌ಗಳನ್ನು ನೋಡಲು ವೈದ್ಯರನ್ನು ಬುಕ್ ಮಾಡಿ',
      upcoming: 'ಮುಂಬರುವ',
      reminderSet: 'ರಿಮೈಂಡರ್ ಸೆಟ್ ಆಗಿದೆ',
    },
  },
  bn: {
    title: 'রিমাইন্ডার',
    subtitle: 'আপনার ওষুধ ও অ্যাপয়েন্টমেন্টের দিকে নজর রাখুন',
    add: 'যুক্ত করুন',
    errorPrefix: 'ত্রুটি',
    notifBanner: {
      title: 'বিজ্ঞপ্তি চালু করুন',
      blocked: 'বিজ্ঞপ্তি ব্লক করা আছে — ডিভাইস সেটিংস → অ্যাপস → MediInfo-এ চালু করুন',
      prompt: 'ঠিক সময়ে ওষুধের রিমাইন্ডার পান',
      allow: 'অনুমতি দিন',
      activeTitle: 'বিজ্ঞপ্তি সক্রিয়',
      activeSub: 'রিমাইন্ডার নির্ধারিত সময়েই আসবে',
    },
    stats: { total: 'মোট', active: 'সক্রিয়', takenToday: 'আজ নেওয়া হয়েছে' },
    tabs: { medicine: 'ওষুধ', appointments: 'অ্যাপয়েন্টমেন্ট' },
    status: { active: 'সক্রিয়', expired: 'মেয়াদ শেষ' },
    form: {
      newTitle: 'নতুন ওষুধ রিমাইন্ডার',
      medicineName: 'ওষুধের নাম',
      medicineNamePlaceholder: 'যেমন Paracetamol',
      dosage: 'মাত্রা',
      dosagePlaceholder: 'যেমন 500mg',
      reminderTime: 'রিমাইন্ডার সময়',
      frequency: 'ফ্রিকোয়েন্সি',
      startDate: 'শুরুর তারিখ',
      endDate: 'শেষের তারিখ',
      notes: 'নোট',
      notesPlaceholder: 'যেমন খাবার পরে নিন',
      save: 'রিমাইন্ডার সংরক্ষণ করুন',
    },
    frequencies: {
      daily: 'প্রতিদিন',
      twiceDaily: 'দিনে দুইবার',
      threeTimesDaily: 'দিনে তিনবার',
      weekly: 'সাপ্তাহিক',
      asNeeded: 'প্রয়োজন অনুযায়ী',
    },
    empty: { title: 'এখনও কোনো রিমাইন্ডার নেই', subtitle: 'শুরু করতে "+ যুক্ত করুন" চাপুন' },
    markTaken: 'নেওয়া হয়েছে চিহ্নিত করুন',
    taken: 'নেওয়া হয়েছে',
    delete: 'মুছুন',
    appointments: {
      emptyTitle: 'কোনো আসন্ন অ্যাপয়েন্টমেন্ট নেই',
      emptySubtitle: 'রিমাইন্ডার দেখতে একজন ডাক্তার বুক করুন',
      upcoming: 'আসন্ন',
      reminderSet: 'রিমাইন্ডার সেট করা আছে',
    },
  },
  ml: {
    title: 'റിമൈൻഡറുകൾ',
    subtitle: 'നിങ്ങളുടെ മരുന്നുകളും അപ്പോയിന്റ്മെന്റുകളും ശ്രദ്ധിക്കുക',
    add: 'ചേർക്കുക',
    errorPrefix: 'പിശക്',
    notifBanner: {
      title: 'അറിയിപ്പുകൾ അനുവദിക്കുക',
      blocked: 'അറിയിപ്പുകൾ ബ്ലോക്ക് ചെയ്തിരിക്കുന്നു — ഡിവൈസ് സെറ്റിംഗ്സ് → ആപ്സ് → MediInfo ൽ പ്രവർത്തനക്ഷമമാക്കുക',
      prompt: 'ശരിയായ സമയത്ത് മരുന്ന് റിമൈൻഡറുകൾ നേടുക',
      allow: 'അനുവദിക്കുക',
      activeTitle: 'അറിയിപ്പുകൾ സജീവമാണ്',
      activeSub: 'റിമൈൻഡറുകൾ നിശ്ചിത സമയത്ത് മാത്രം വരും',
    },
    stats: { total: 'ആകെ', active: 'സജീവം', takenToday: 'ഇന്ന് എടുത്തത്' },
    tabs: { medicine: 'മരുന്ന്', appointments: 'അപ്പോയിന്റ്മെന്റുകൾ' },
    status: { active: 'സജീവം', expired: 'കാലഹരണപ്പെട്ടു' },
    form: {
      newTitle: 'പുതിയ മരുന്ന് റിമൈൻഡർ',
      medicineName: 'മരുന്നിന്റെ പേര്',
      medicineNamePlaceholder: 'ഉദാ. Paracetamol',
      dosage: 'അളവ്',
      dosagePlaceholder: 'ഉദാ. 500mg',
      reminderTime: 'റിമൈൻഡർ സമയം',
      frequency: 'ഫ്രീക്വൻസി',
      startDate: 'തുടക്ക തീയതി',
      endDate: 'അവസാന തീയതി',
      notes: 'കുറിപ്പുകൾ',
      notesPlaceholder: 'ഉദാ. ഭക്ഷണത്തിന് ശേഷം കഴിക്കുക',
      save: 'റിമൈൻഡർ സംരക്ഷിക്കുക',
    },
    frequencies: {
      daily: 'ദിവസേന',
      twiceDaily: 'ദിവസത്തിൽ രണ്ടുതവണ',
      threeTimesDaily: 'ദിവസത്തിൽ മൂന്നുതവണ',
      weekly: 'പ്രതിവാരം',
      asNeeded: 'ആവശ്യമുള്ളപ്പോൾ',
    },
    empty: { title: 'ഇതുവരെ റിമൈൻഡറുകൾ ഇല്ല', subtitle: 'തുടങ്ങാൻ "+ ചേർക്കുക" അമർത്തുക' },
    markTaken: 'എടുത്തതായി അടയാളപ്പെടുത്തുക',
    taken: 'എടുത്തത്',
    delete: 'നീക്കം ചെയ്യുക',
    appointments: {
      emptyTitle: 'വരാനിരിക്കുന്ന അപ്പോയിന്റ്മെന്റുകൾ ഇല്ല',
      emptySubtitle: 'റിമൈൻഡറുകൾ കാണാൻ ഒരു ഡോക്ടറെ ബുക്ക് ചെയ്യുക',
      upcoming: 'വരാനിരിക്കുന്നത്',
      reminderSet: 'റിമൈൻഡർ സെറ്റ് ചെയ്തിട്ടുണ്ട്',
    },
  },
  gu: {
    title: 'રિમાઇન્ડર',
    subtitle: 'તમારી દવાઓ અને એપોઇન્ટમેન્ટ પર ધ્યાન રાખો',
    add: 'ઉમેરો',
    errorPrefix: 'ભૂલ',
    notifBanner: {
      title: 'સૂચનાઓ ચાલુ કરો',
      blocked: 'સૂચનાઓ અવરોધિત છે — ડિવાઇસ સેટિંગ્સ → એપ્સ → MediInfo માં સક્રિય કરો',
      prompt: 'યોગ્ય સમયે દવા રિમાઇન્ડર મેળવો',
      allow: 'મંજૂરી આપો',
      activeTitle: 'સૂચનાઓ સક્રિય છે',
      activeSub: 'રિમાઇન્ડર નિર્ધારિત સમયે જ આવશે',
    },
    stats: { total: 'કુલ', active: 'સક્રિય', takenToday: 'આજે લેવાયું' },
    tabs: { medicine: 'દવા', appointments: 'એપોઇન્ટમેન્ટ' },
    status: { active: 'સક્રિય', expired: 'સમાપ્ત' },
    form: {
      newTitle: 'નવું દવા રિમાઇન્ડર',
      medicineName: 'દવાનું નામ',
      medicineNamePlaceholder: 'દા.ત. Paracetamol',
      dosage: 'માત્રા',
      dosagePlaceholder: 'દા.ત. 500mg',
      reminderTime: 'રિમાઇન્ડર સમય',
      frequency: 'આવર્તન',
      startDate: 'શરૂઆતની તારીખ',
      endDate: 'સમાપ્તિ તારીખ',
      notes: 'નોંધ',
      notesPlaceholder: 'દા.ત. ભોજન પછી લો',
      save: 'રિમાઇન્ડર સાચવો',
    },
    frequencies: {
      daily: 'દરરોજ',
      twiceDaily: 'દિવસમાં બે વાર',
      threeTimesDaily: 'દિવસમાં ત્રણ વાર',
      weekly: 'સાપ્તાહિક',
      asNeeded: 'જરૂર પ્રમાણે',
    },
    empty: { title: 'હજુ સુધી કોઈ રિમાઇન્ડર નથી', subtitle: 'શરૂ કરવા માટે "+ ઉમેરો" દબાવો' },
    markTaken: 'લેવાયું તેમ ચિહ્નિત કરો',
    taken: 'લેવાયું',
    delete: 'દૂર કરો',
    appointments: {
      emptyTitle: 'કોઈ આવનારી એપોઇન્ટમેન્ટ નથી',
      emptySubtitle: 'રિમાઇન્ડર જોવા માટે ડૉક્ટર બુક કરો',
      upcoming: 'આવનારી',
      reminderSet: 'રિમાઇન્ડર સેટ છે',
    },
  },
  pa: {
    title: 'ਰਿਮਾਈਂਡਰ',
    subtitle: 'ਆਪਣੀਆਂ ਦਵਾਈਆਂ ਅਤੇ ਮੁਲਾਕਾਤਾਂ ਦਾ ਧਿਆਨ ਰੱਖੋ',
    add: 'ਜੋੜੋ',
    errorPrefix: 'ਗਲਤੀ',
    notifBanner: {
      title: 'ਸੂਚਨਾਵਾਂ ਚਾਲੂ ਕਰੋ',
      blocked: 'ਸੂਚਨਾਵਾਂ ਬਲੌਕ ਹਨ — ਡਿਵਾਈਸ ਸੈਟਿੰਗਜ਼ → ਐਪਸ → MediInfo ਵਿੱਚ ਚਾਲੂ ਕਰੋ',
      prompt: 'ਸਹੀ ਸਮੇਂ ਤੇ ਦਵਾਈ ਰਿਮਾਈਂਡਰ ਪਾਓ',
      allow: 'ਇਜਾਜ਼ਤ ਦਿਓ',
      activeTitle: 'ਸੂਚਨਾਵਾਂ ਸਰਗਰਮ ਹਨ',
      activeSub: 'ਰਿਮਾਈਂਡਰ ਤੈਅ ਸਮੇਂ ਤੇ ਹੀ ਆਉਣਗੇ',
    },
    stats: { total: 'ਕੁੱਲ', active: 'ਸਰਗਰਮ', takenToday: 'ਅੱਜ ਲਈ ਗਈ' },
    tabs: { medicine: 'ਦਵਾਈ', appointments: 'ਮੁਲਾਕਾਤਾਂ' },
    status: { active: 'ਸਰਗਰਮ', expired: 'ਸਮਾਪਤ' },
    form: {
      newTitle: 'ਨਵਾਂ ਦਵਾਈ ਰਿਮਾਈਂਡਰ',
      medicineName: 'ਦਵਾਈ ਦਾ ਨਾਮ',
      medicineNamePlaceholder: 'ਜਿਵੇਂ Paracetamol',
      dosage: 'ਮਾਤਰਾ',
      dosagePlaceholder: 'ਜਿਵੇਂ 500mg',
      reminderTime: 'ਰਿਮਾਈਂਡਰ ਸਮਾਂ',
      frequency: 'ਫ੍ਰੀਕੁਐਂਸੀ',
      startDate: 'ਸ਼ੁਰੂ ਮਿਤੀ',
      endDate: 'ਸਮਾਪਤੀ ਮਿਤੀ',
      notes: 'ਨੋਟਸ',
      notesPlaceholder: 'ਜਿਵੇਂ ਖਾਣੇ ਤੋਂ ਬਾਅਦ ਲਓ',
      save: 'ਰਿਮਾਈਂਡਰ ਸੇਵ ਕਰੋ',
    },
    frequencies: {
      daily: 'ਰੋਜ਼ਾਨਾ',
      twiceDaily: 'ਦਿਨ ਵਿੱਚ ਦੋ ਵਾਰ',
      threeTimesDaily: 'ਦਿਨ ਵਿੱਚ ਤਿੰਨ ਵਾਰ',
      weekly: 'ਹਫ਼ਤਾਵਾਰੀ',
      asNeeded: 'ਲੋੜ ਅਨੁਸਾਰ',
    },
    empty: { title: 'ਅਜੇ ਕੋਈ ਰਿਮਾਈਂਡਰ ਨਹੀਂ', subtitle: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ "+ ਜੋੜੋ" ਦਬਾਓ' },
    markTaken: 'ਲਈ ਗਈ ਵਜੋਂ ਚਿੰਨ੍ਹਿਤ ਕਰੋ',
    taken: 'ਲਈ ਗਈ',
    delete: 'ਮਿਟਾਓ',
    appointments: {
      emptyTitle: 'ਕੋਈ ਆਉਣ ਵਾਲੀ ਮੁਲਾਕਾਤ ਨਹੀਂ',
      emptySubtitle: 'ਰਿਮਾਈਂਡਰ ਦੇਖਣ ਲਈ ਡਾਕਟਰ ਬੁੱਕ ਕਰੋ',
      upcoming: 'ਆਉਣ ਵਾਲੀ',
      reminderSet: 'ਰਿਮਾਈਂਡਰ ਸੈੱਟ ਹੈ',
    },
  },
}

let updatedCount = 0

for (const lang of ['en', 'hi', 'mr', 'ta', 'te', 'kn', 'bn', 'ml', 'gu', 'pa']) {
  const filePath = path.join(LOCALES_DIR, `${lang}.json`)

  if (!fs.existsSync(filePath)) {
    console.log(`⚠️  Skipping ${lang}.json — file not found`)
    continue
  }

  const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'))

  if (data.reminders !== undefined) {
    console.log(`ℹ️  ${lang}.json already has a "reminders" key — left untouched`)
    continue
  }

  data.reminders = lang === 'en' ? REMINDERS_EN : TRANSLATIONS[lang]
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf-8')
  console.log(`✅ Added reminders namespace to ${lang}.json`)
  updatedCount++
}

console.log(`\nDone. ${updatedCount} file(s) updated.`)
console.log('Run "node check_i18n_keys.js src/i18n/locales" to verify key counts are in sync.')