// add_doctors_keys.js
// Usage: node add_doctors_keys.js src/i18n/locales
// Adds a new "doctors" namespace to every locale JSON file (merges, doesn't overwrite existing keys).

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOCALES_DIR = process.argv[2] || __dirname;

const DOCTORS_NS = {
  en: {
    title: "Find a Doctor",
    subtitle: "Browse and book appointments",
    viewAppointments: "View Appointments",
    requestSent: "Appointment request sent to Dr. {{name}}! Awaiting clinic approval.",
    loadingDoctors: "Loading doctors…",
    noDoctors: "No doctors found",
    noDoctorsSub: "Try a different specialization or expand your search area",
    sortedByDistance: "Sorted by distance from your location",
    distanceAway: "{{distance}} km away",
    book: "Book",
    bookAppointment: "Book Appointment",
    fee: "Fee",
    selectDate: "Select Date",
    selectTimeSlot: "Select Time Slot",
    selectDateFirst: "Please select a date first",
    loadingSlots: "Loading available slots...",
    noAvailability: "No availability on this day",
    scrollMore: "Scroll to see more slots",
    describeIssue: "Describe your issue (optional)",
    issuePlaceholder: "e.g. Fever and headache for 2 days…",
    booking: "Booking…",
    requestAppointment: "Request Appointment — ₹{{fee}}",
    selectDateTimeError: "Please select date and time",
    slotBookedError: "This slot is already booked",
    duplicateApptError: "You already have an appointment at this time",
    bookFailError: "Failed to book appointment. Please try again.",
    specializations: {
      all: "All",
      generalPhysician: "General Physician",
      cardiologist: "Cardiologist",
      dermatologist: "Dermatologist",
      neurologist: "Neurologist",
      orthopedic: "Orthopedic",
      pediatrician: "Pediatrician",
      psychiatrist: "Psychiatrist",
      ent: "ENT"
    }
  },
  hi: {
    title: "डॉक्टर खोजें",
    subtitle: "अपॉइंटमेंट ब्राउज़ करें और बुक करें",
    viewAppointments: "अपॉइंटमेंट देखें",
    requestSent: "डॉ. {{name}} को अपॉइंटमेंट का अनुरोध भेजा गया! क्लिनिक की मंजूरी का इंतज़ार है।",
    loadingDoctors: "डॉक्टर लोड हो रहे हैं…",
    noDoctors: "कोई डॉक्टर नहीं मिला",
    noDoctorsSub: "कोई अलग विशेषज्ञता चुनें या खोज क्षेत्र बढ़ाएं",
    sortedByDistance: "आपके स्थान से दूरी के अनुसार क्रमबद्ध",
    distanceAway: "{{distance}} किमी दूर",
    book: "बुक करें",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    fee: "शुल्क",
    selectDate: "तारीख चुनें",
    selectTimeSlot: "समय स्लॉट चुनें",
    selectDateFirst: "कृपया पहले तारीख चुनें",
    loadingSlots: "उपलब्ध स्लॉट लोड हो रहे हैं...",
    noAvailability: "इस दिन कोई उपलब्धता नहीं",
    scrollMore: "और स्लॉट देखने के लिए स्क्रॉल करें",
    describeIssue: "अपनी समस्या बताएं (वैकल्पिक)",
    issuePlaceholder: "जैसे: 2 दिनों से बुखार और सिरदर्द…",
    booking: "बुक हो रहा है…",
    requestAppointment: "अपॉइंटमेंट का अनुरोध — ₹{{fee}}",
    selectDateTimeError: "कृपया तारीख और समय चुनें",
    slotBookedError: "यह स्लॉट पहले से बुक है",
    duplicateApptError: "इस समय आपकी पहले से एक अपॉइंटमेंट है",
    bookFailError: "अपॉइंटमेंट बुक करने में विफल। कृपया पुनः प्रयास करें।",
    specializations: {
      all: "सभी",
      generalPhysician: "जनरल फिजिशियन",
      cardiologist: "हृदय रोग विशेषज्ञ",
      dermatologist: "त्वचा रोग विशेषज्ञ",
      neurologist: "न्यूरोलॉजिस्ट",
      orthopedic: "हड्डी रोग विशेषज्ञ",
      pediatrician: "बाल रोग विशेषज्ञ",
      psychiatrist: "मनोचिकित्सक",
      ent: "ईएनटी"
    }
  },
  mr: {
    title: "डॉक्टर शोधा",
    subtitle: "अपॉइंटमेंट ब्राउझ करा आणि बुक करा",
    viewAppointments: "अपॉइंटमेंट पहा",
    requestSent: "डॉ. {{name}} यांना अपॉइंटमेंटची विनंती पाठवली! क्लिनिकच्या मंजुरीची प्रतीक्षा आहे.",
    loadingDoctors: "डॉक्टर लोड होत आहेत…",
    noDoctors: "कोणतेही डॉक्टर सापडले नाहीत",
    noDoctorsSub: "वेगळी स्पेशलायझेशन निवडा किंवा शोध क्षेत्र वाढवा",
    sortedByDistance: "तुमच्या स्थानापासूनच्या अंतरानुसार क्रमवारी",
    distanceAway: "{{distance}} किमी दूर",
    book: "बुक करा",
    bookAppointment: "अपॉइंटमेंट बुक करा",
    fee: "फी",
    selectDate: "तारीख निवडा",
    selectTimeSlot: "वेळ स्लॉट निवडा",
    selectDateFirst: "कृपया आधी तारीख निवडा",
    loadingSlots: "उपलब्ध स्लॉट लोड होत आहेत...",
    noAvailability: "या दिवशी उपलब्धता नाही",
    scrollMore: "अधिक स्लॉट पाहण्यासाठी स्क्रोल करा",
    describeIssue: "तुमची समस्या सांगा (पर्यायी)",
    issuePlaceholder: "उदा. 2 दिवसांपासून ताप आणि डोकेदुखी…",
    booking: "बुक होत आहे…",
    requestAppointment: "अपॉइंटमेंटची विनंती — ₹{{fee}}",
    selectDateTimeError: "कृपया तारीख आणि वेळ निवडा",
    slotBookedError: "हा स्लॉट आधीच बुक झाला आहे",
    duplicateApptError: "या वेळी तुमची आधीच एक अपॉइंटमेंट आहे",
    bookFailError: "अपॉइंटमेंट बुक करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    specializations: {
      all: "सर्व",
      generalPhysician: "जनरल फिजिशियन",
      cardiologist: "हृदयरोग तज्ज्ञ",
      dermatologist: "त्वचारोग तज्ज्ञ",
      neurologist: "न्यूरोलॉजिस्ट",
      orthopedic: "हाडरोग तज्ज्ञ",
      pediatrician: "बालरोग तज्ज्ञ",
      psychiatrist: "मनोविकार तज्ज्ञ",
      ent: "ईएनटी"
    }
  },
  ta: {
    title: "மருத்துவரைத் தேடுங்கள்",
    subtitle: "அப்பாயிண்ட்மென்ட்களை உலாவி பதிவு செய்யுங்கள்",
    viewAppointments: "அப்பாயிண்ட்மென்ட்களைப் பார்க்க",
    requestSent: "டாக்டர் {{name}} அவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது! கிளினிக் ஒப்புதலுக்காக காத்திருக்கிறது.",
    loadingDoctors: "மருத்துவர்கள் ஏற்றப்படுகிறது…",
    noDoctors: "மருத்துவர்கள் எவரும் கிடைக்கவில்லை",
    noDoctorsSub: "வேறு சிறப்புத்துறையை முயற்சிக்கவும் அல்லது தேடல் பகுதியை விரிவாக்கவும்",
    sortedByDistance: "உங்கள் இருப்பிடத்திலிருந்து தூரத்தின் அடிப்படையில் வரிசைப்படுத்தப்பட்டது",
    distanceAway: "{{distance}} கி.மீ தொலைவில்",
    book: "பதிவு செய்",
    bookAppointment: "அப்பாயிண்ட்மென்ட் பதிவு செய்",
    fee: "கட்டணம்",
    selectDate: "தேதியைத் தேர்ந்தெடுக்கவும்",
    selectTimeSlot: "நேர இடைவெளியைத் தேர்ந்தெடுக்கவும்",
    selectDateFirst: "முதலில் தேதியைத் தேர்ந்தெடுக்கவும்",
    loadingSlots: "கிடைக்கும் நேரங்கள் ஏற்றப்படுகின்றன...",
    noAvailability: "இந்த நாளில் கிடைக்கவில்லை",
    scrollMore: "மேலும் நேரங்களைப் பார்க்க ஸ்க்ரோல் செய்யவும்",
    describeIssue: "உங்கள் பிரச்சினையை விவரிக்கவும் (விருப்பத்தேர்வு)",
    issuePlaceholder: "எ.கா. 2 நாட்களாக காய்ச்சல் மற்றும் தலைவலி…",
    booking: "பதிவு செய்யப்படுகிறது…",
    requestAppointment: "அப்பாயிண்ட்மென்ட் கோரிக்கை — ₹{{fee}}",
    selectDateTimeError: "தேதி மற்றும் நேரத்தைத் தேர்ந்தெடுக்கவும்",
    slotBookedError: "இந்த நேரம் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது",
    duplicateApptError: "இந்த நேரத்தில் உங்களுக்கு ஏற்கனவே ஒரு அப்பாயிண்ட்மென்ட் உள்ளது",
    bookFailError: "அப்பாயிண்ட்மென்ட் பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
    specializations: {
      all: "அனைத்தும்",
      generalPhysician: "பொது மருத்துவர்",
      cardiologist: "இதயநோய் நிபுணர்",
      dermatologist: "தோல் நோய் நிபுணர்",
      neurologist: "நரம்பியல் நிபுணர்",
      orthopedic: "எலும்பியல் நிபுணர்",
      pediatrician: "குழந்தை மருத்துவர்",
      psychiatrist: "மனநல மருத்துவர்",
      ent: "காது மூக்கு தொண்டை"
    }
  },
  te: {
    title: "డాక్టర్‌ను కనుగొనండి",
    subtitle: "అపాయింట్‌మెంట్‌లను బ్రౌజ్ చేసి బుక్ చేయండి",
    viewAppointments: "అపాయింట్‌మెంట్‌లను చూడండి",
    requestSent: "డా. {{name}} కి అపాయింట్‌మెంట్ అభ్యర్థన పంపబడింది! క్లినిక్ ఆమోదం కోసం వేచి ఉంది.",
    loadingDoctors: "డాక్టర్లు లోడ్ అవుతున్నారు…",
    noDoctors: "డాక్టర్లు కనుగొనబడలేదు",
    noDoctorsSub: "వేరే స్పెషలైజేషన్ ప్రయత్నించండి లేదా శోధన ప్రాంతాన్ని విస్తరించండి",
    sortedByDistance: "మీ స్థానం నుండి దూరం ఆధారంగా క్రమబద్ధీకరించబడింది",
    distanceAway: "{{distance}} కి.మీ దూరంలో",
    book: "బుక్ చేయండి",
    bookAppointment: "అపాయింట్‌మెంట్ బుక్ చేయండి",
    fee: "ఫీజు",
    selectDate: "తేదీని ఎంచుకోండి",
    selectTimeSlot: "సమయ స్లాట్‌ను ఎంచుకోండి",
    selectDateFirst: "దయచేసి ముందుగా తేదీని ఎంచుకోండి",
    loadingSlots: "అందుబాటులో ఉన్న స్లాట్‌లు లోడ్ అవుతున్నాయి...",
    noAvailability: "ఈ రోజు అందుబాటులో లేదు",
    scrollMore: "మరిన్ని స్లాట్‌లను చూడటానికి స్క్రోల్ చేయండి",
    describeIssue: "మీ సమస్యను వివరించండి (ఐచ్ఛికం)",
    issuePlaceholder: "ఉదా. 2 రోజులుగా జ్వరం మరియు తలనొప్పి…",
    booking: "బుక్ చేయబడుతోంది…",
    requestAppointment: "అపాయింట్‌మెంట్ అభ్యర్థన — ₹{{fee}}",
    selectDateTimeError: "దయచేసి తేదీ మరియు సమయాన్ని ఎంచుకోండి",
    slotBookedError: "ఈ స్లాట్ ఇప్పటికే బుక్ చేయబడింది",
    duplicateApptError: "ఈ సమయంలో మీకు ఇప్పటికే ఒక అపాయింట్‌మెంట్ ఉంది",
    bookFailError: "అపాయింట్‌మెంట్ బుక్ చేయడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    specializations: {
      all: "అన్నీ",
      generalPhysician: "జనరల్ ఫిజీషియన్",
      cardiologist: "హృదయ నిపుణుడు",
      dermatologist: "చర్మ వ్యాధి నిపుణుడు",
      neurologist: "న్యూరాలజిస్ట్",
      orthopedic: "ఎముకల నిపుణుడు",
      pediatrician: "పిల్లల వైద్యుడు",
      psychiatrist: "మానసిక వైద్యుడు",
      ent: "ఈఎన్‌టీ"
    }
  },
  kn: {
    title: "ವೈದ್ಯರನ್ನು ಹುಡುಕಿ",
    subtitle: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ ಮತ್ತು ಬುಕ್ ಮಾಡಿ",
    viewAppointments: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    requestSent: "ಡಾ. {{name}} ಗೆ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ! ಕ್ಲಿನಿಕ್ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ.",
    loadingDoctors: "ವೈದ್ಯರು ಲೋಡ್ ಆಗುತ್ತಿದ್ದಾರೆ…",
    noDoctors: "ಯಾವುದೇ ವೈದ್ಯರು ಕಂಡುಬಂದಿಲ್ಲ",
    noDoctorsSub: "ಬೇರೆ ವಿಶೇಷತೆಯನ್ನು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಹುಡುಕಾಟ ಪ್ರದೇಶವನ್ನು ವಿಸ್ತರಿಸಿ",
    sortedByDistance: "ನಿಮ್ಮ ಸ್ಥಳದಿಂದ ದೂರದ ಆಧಾರದ ಮೇಲೆ ವಿಂಗಡಿಸಲಾಗಿದೆ",
    distanceAway: "{{distance}} ಕಿ.ಮೀ ದೂರದಲ್ಲಿ",
    book: "ಬುಕ್ ಮಾಡಿ",
    bookAppointment: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ",
    fee: "ಶುಲ್ಕ",
    selectDate: "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    selectTimeSlot: "ಸಮಯದ ಸ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ",
    selectDateFirst: "ದಯವಿಟ್ಟು ಮೊದಲು ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    loadingSlots: "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್‌ಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
    noAvailability: "ಈ ದಿನ ಯಾವುದೇ ಲಭ್ಯತೆ ಇಲ್ಲ",
    scrollMore: "ಹೆಚ್ಚಿನ ಸ್ಲಾಟ್‌ಗಳನ್ನು ನೋಡಲು ಸ್ಕ್ರಾಲ್ ಮಾಡಿ",
    describeIssue: "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ (ಐಚ್ಛಿಕ)",
    issuePlaceholder: "ಉದಾ. 2 ದಿನಗಳಿಂದ ಜ್ವರ ಮತ್ತು ತಲೆನೋವು…",
    booking: "ಬುಕ್ ಆಗುತ್ತಿದೆ…",
    requestAppointment: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ವಿನಂತಿ — ₹{{fee}}",
    selectDateTimeError: "ದಯವಿಟ್ಟು ದಿನಾಂಕ ಮತ್ತು ಸಮಯ ಆಯ್ಕೆಮಾಡಿ",
    slotBookedError: "ಈ ಸ್ಲಾಟ್ ಈಗಾಗಲೇ ಬುಕ್ ಆಗಿದೆ",
    duplicateApptError: "ಈ ಸಮಯದಲ್ಲಿ ನಿಮಗೆ ಈಗಾಗಲೇ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಇದೆ",
    bookFailError: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    specializations: {
      all: "ಎಲ್ಲಾ",
      generalPhysician: "ಜನರಲ್ ಫಿಸಿಶಿಯನ್",
      cardiologist: "ಹೃದ್ರೋಗ ತಜ್ಞ",
      dermatologist: "ಚರ್ಮರೋಗ ತಜ್ಞ",
      neurologist: "ನರರೋಗ ತಜ್ಞ",
      orthopedic: "ಮೂಳೆ ತಜ್ಞ",
      pediatrician: "ಮಕ್ಕಳ ವೈದ್ಯ",
      psychiatrist: "ಮನೋವೈದ್ಯ",
      ent: "ಇಎನ್‌ಟಿ"
    }
  },
  bn: {
    title: "ডাক্তার খুঁজুন",
    subtitle: "অ্যাপয়েন্টমেন্ট ব্রাউজ করুন এবং বুক করুন",
    viewAppointments: "অ্যাপয়েন্টমেন্ট দেখুন",
    requestSent: "ডা. {{name}} কে অ্যাপয়েন্টমেন্টের অনুরোধ পাঠানো হয়েছে! ক্লিনিকের অনুমোদনের অপেক্ষায়।",
    loadingDoctors: "ডাক্তার লোড হচ্ছে…",
    noDoctors: "কোনো ডাক্তার পাওয়া যায়নি",
    noDoctorsSub: "ভিন্ন বিশেষত্ব চেষ্টা করুন বা অনুসন্ধান এলাকা বাড়ান",
    sortedByDistance: "আপনার অবস্থান থেকে দূরত্ব অনুযায়ী সাজানো",
    distanceAway: "{{distance}} কিমি দূরে",
    book: "বুক করুন",
    bookAppointment: "অ্যাপয়েন্টমেন্ট বুক করুন",
    fee: "ফি",
    selectDate: "তারিখ নির্বাচন করুন",
    selectTimeSlot: "সময়ের স্লট নির্বাচন করুন",
    selectDateFirst: "অনুগ্রহ করে প্রথমে তারিখ নির্বাচন করুন",
    loadingSlots: "উপলব্ধ স্লট লোড হচ্ছে...",
    noAvailability: "এই দিনে কোনো উপলব্ধতা নেই",
    scrollMore: "আরও স্লট দেখতে স্ক্রোল করুন",
    describeIssue: "আপনার সমস্যা বর্ণনা করুন (ঐচ্ছিক)",
    issuePlaceholder: "যেমন: ২ দিন ধরে জ্বর এবং মাথাব্যথা…",
    booking: "বুক হচ্ছে…",
    requestAppointment: "অ্যাপয়েন্টমেন্টের অনুরোধ — ₹{{fee}}",
    selectDateTimeError: "অনুগ্রহ করে তারিখ এবং সময় নির্বাচন করুন",
    slotBookedError: "এই স্লটটি ইতিমধ্যে বুক করা হয়েছে",
    duplicateApptError: "এই সময়ে আপনার ইতিমধ্যে একটি অ্যাপয়েন্টমেন্ট আছে",
    bookFailError: "অ্যাপয়েন্টমেন্ট বুক করতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    specializations: {
      all: "সব",
      generalPhysician: "জেনারেল ফিজিশিয়ান",
      cardiologist: "হৃদরোগ বিশেষজ্ঞ",
      dermatologist: "চর্মরোগ বিশেষজ্ঞ",
      neurologist: "স্নায়ুরোগ বিশেষজ্ঞ",
      orthopedic: "অস্থি বিশেষজ্ঞ",
      pediatrician: "শিশু বিশেষজ্ঞ",
      psychiatrist: "মনোরোগ বিশেষজ্ঞ",
      ent: "ইএনটি"
    }
  },
  ml: {
    title: "ഡോക്ടറെ കണ്ടെത്തുക",
    subtitle: "അപ്പോയിന്റ്മെന്റുകൾ ബ്രൗസ് ചെയ്ത് ബുക്ക് ചെയ്യുക",
    viewAppointments: "അപ്പോയിന്റ്മെന്റുകൾ കാണുക",
    requestSent: "ഡോ. {{name}} ന് അപ്പോയിന്റ്മെന്റ് അഭ്യർത്ഥന അയച്ചു! ക്ലിനിക്കിന്റെ അംഗീകാരത്തിനായി കാത്തിരിക്കുന്നു.",
    loadingDoctors: "ഡോക്ടർമാരെ ലോഡ് ചെയ്യുന്നു…",
    noDoctors: "ഡോക്ടർമാരെ കണ്ടെത്തിയില്ല",
    noDoctorsSub: "മറ്റൊരു സ്പെഷ്യലൈസേഷൻ ശ്രമിക്കുക അല്ലെങ്കിൽ തിരയൽ പ്രദേശം വിപുലീകരിക്കുക",
    sortedByDistance: "നിങ്ങളുടെ സ്ഥലത്ത് നിന്നുള്ള ദൂരം അനുസരിച്ച് ക്രമീകരിച്ചിരിക്കുന്നു",
    distanceAway: "{{distance}} കി.മീ അകലെ",
    book: "ബുക്ക് ചെയ്യുക",
    bookAppointment: "അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക",
    fee: "ഫീസ്",
    selectDate: "തീയതി തിരഞ്ഞെടുക്കുക",
    selectTimeSlot: "സമയ സ്ലോട്ട് തിരഞ്ഞെടുക്കുക",
    selectDateFirst: "ദയവായി ആദ്യം തീയതി തിരഞ്ഞെടുക്കുക",
    loadingSlots: "ലഭ്യമായ സ്ലോട്ടുകൾ ലോഡ് ചെയ്യുന്നു...",
    noAvailability: "ഈ ദിവസം ലഭ്യതയില്ല",
    scrollMore: "കൂടുതൽ സ്ലോട്ടുകൾ കാണാൻ സ്ക്രോൾ ചെയ്യുക",
    describeIssue: "നിങ്ങളുടെ പ്രശ്നം വിവരിക്കുക (ഓപ്ഷണൽ)",
    issuePlaceholder: "ഉദാ: 2 ദിവസമായി പനിയും തലവേദനയും…",
    booking: "ബുക്ക് ചെയ്യുന്നു…",
    requestAppointment: "അപ്പോയിന്റ്മെന്റ് അഭ്യർത്ഥന — ₹{{fee}}",
    selectDateTimeError: "ദയവായി തീയതിയും സമയവും തിരഞ്ഞെടുക്കുക",
    slotBookedError: "ഈ സ്ലോട്ട് ഇതിനകം ബുക്ക് ചെയ്തിട്ടുണ്ട്",
    duplicateApptError: "ഈ സമയത്ത് നിങ്ങൾക്ക് ഇതിനകം ഒരു അപ്പോയിന്റ്മെന്റ് ഉണ്ട്",
    bookFailError: "അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക.",
    specializations: {
      all: "എല്ലാം",
      generalPhysician: "ജനറൽ ഫിസിഷ്യൻ",
      cardiologist: "ഹൃദ്രോഗ വിദഗ്ധൻ",
      dermatologist: "ത്വക്ക് രോഗ വിദഗ്ധൻ",
      neurologist: "ന്യൂറോളജിസ്റ്റ്",
      orthopedic: "അസ്ഥി രോഗ വിദഗ്ധൻ",
      pediatrician: "ശിശുരോഗ വിദഗ്ധൻ",
      psychiatrist: "മാനസികരോഗ വിദഗ്ധൻ",
      ent: "ഇഎൻടി"
    }
  },
  gu: {
    title: "ડૉક્ટર શોધો",
    subtitle: "એપોઇન્ટમેન્ટ બ્રાઉઝ કરો અને બુક કરો",
    viewAppointments: "એપોઇન્ટમેન્ટ જુઓ",
    requestSent: "ડૉ. {{name}} ને એપોઇન્ટમેન્ટની વિનંતી મોકલવામાં આવી! ક્લિનિકની મંજૂરીની રાહ જોવાઈ રહી છે.",
    loadingDoctors: "ડૉક્ટરો લોડ થઈ રહ્યા છે…",
    noDoctors: "કોઈ ડૉક્ટર મળ્યા નથી",
    noDoctorsSub: "અલગ વિશેષતા અજમાવો અથવા શોધ વિસ્તાર વધારો",
    sortedByDistance: "તમારા સ્થાનથી અંતર પ્રમાણે ક્રમબદ્ધ",
    distanceAway: "{{distance}} કિમી દૂર",
    book: "બુક કરો",
    bookAppointment: "એપોઇન્ટમેન્ટ બુક કરો",
    fee: "ફી",
    selectDate: "તારીખ પસંદ કરો",
    selectTimeSlot: "સમય સ્લોટ પસંદ કરો",
    selectDateFirst: "કૃપા કરી પહેલા તારીખ પસંદ કરો",
    loadingSlots: "ઉપલબ્ધ સ્લોટ લોડ થઈ રહ્યા છે...",
    noAvailability: "આ દિવસે કોઈ ઉપલબ્ધતા નથી",
    scrollMore: "વધુ સ્લોટ જોવા સ્ક્રોલ કરો",
    describeIssue: "તમારી સમસ્યાનું વર્ણન કરો (વૈકલ્પિક)",
    issuePlaceholder: "દા.ત. 2 દિવસથી તાવ અને માથાનો દુખાવો…",
    booking: "બુક થઈ રહ્યું છે…",
    requestAppointment: "એપોઇન્ટમેન્ટ વિનંતી — ₹{{fee}}",
    selectDateTimeError: "કૃપા કરી તારીખ અને સમય પસંદ કરો",
    slotBookedError: "આ સ્લોટ પહેલેથી જ બુક થયેલ છે",
    duplicateApptError: "આ સમયે તમારી પાસે પહેલેથી જ એપોઇન્ટમેન્ટ છે",
    bookFailError: "એપોઇન્ટમેન્ટ બુક કરવામાં નિષ્ફળ. ફરી પ્રયાસ કરો.",
    specializations: {
      all: "બધા",
      generalPhysician: "જનરલ ફિઝિશિયન",
      cardiologist: "હૃદય રોગ નિષ્ણાત",
      dermatologist: "ત્વચા રોગ નિષ્ણાત",
      neurologist: "ન્યુરોલોજિસ્ટ",
      orthopedic: "હાડકાં રોગ નિષ્ણાત",
      pediatrician: "બાળ રોગ નિષ્ણાત",
      psychiatrist: "મનોચિકિત્સક",
      ent: "ઇએનટી"
    }
  },
  pa: {
    title: "ਡਾਕਟਰ ਲੱਭੋ",
    subtitle: "ਅਪਾਇੰਟਮੈਂਟਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ ਅਤੇ ਬੁੱਕ ਕਰੋ",
    viewAppointments: "ਅਪਾਇੰਟਮੈਂਟਾਂ ਵੇਖੋ",
    requestSent: "ਡਾ. {{name}} ਨੂੰ ਅਪਾਇੰਟਮੈਂਟ ਦੀ ਬੇਨਤੀ ਭੇਜੀ ਗਈ! ਕਲੀਨਿਕ ਦੀ ਮਨਜ਼ੂਰੀ ਦੀ ਉਡੀਕ ਹੈ।",
    loadingDoctors: "ਡਾਕਟਰ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…",
    noDoctors: "ਕੋਈ ਡਾਕਟਰ ਨਹੀਂ ਮਿਲਿਆ",
    noDoctorsSub: "ਵੱਖਰੀ ਮਾਹਰਤਾ ਅਜ਼ਮਾਓ ਜਾਂ ਖੋਜ ਖੇਤਰ ਵਧਾਓ",
    sortedByDistance: "ਤੁਹਾਡੇ ਸਥਾਨ ਤੋਂ ਦੂਰੀ ਅਨੁਸਾਰ ਕ੍ਰਮਬੱਧ",
    distanceAway: "{{distance}} ਕਿਮੀ ਦੂਰ",
    book: "ਬੁੱਕ ਕਰੋ",
    bookAppointment: "ਅਪਾਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
    fee: "ਫੀਸ",
    selectDate: "ਤਾਰੀਖ ਚੁਣੋ",
    selectTimeSlot: "ਸਮਾਂ ਸਲਾਟ ਚੁਣੋ",
    selectDateFirst: "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਤਾਰੀਖ ਚੁਣੋ",
    loadingSlots: "ਉਪਲਬਧ ਸਲਾਟ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...",
    noAvailability: "ਇਸ ਦਿਨ ਕੋਈ ਉਪਲਬਧਤਾ ਨਹੀਂ",
    scrollMore: "ਹੋਰ ਸਲਾਟ ਵੇਖਣ ਲਈ ਸਕ੍ਰੋਲ ਕਰੋ",
    describeIssue: "ਆਪਣੀ ਸਮੱਸਿਆ ਦੱਸੋ (ਵਿਕਲਪਿਕ)",
    issuePlaceholder: "ਜਿਵੇਂ: 2 ਦਿਨਾਂ ਤੋਂ ਬੁਖਾਰ ਅਤੇ ਸਿਰ ਦਰਦ…",
    booking: "ਬੁੱਕ ਹੋ ਰਿਹਾ ਹੈ…",
    requestAppointment: "ਅਪਾਇੰਟਮੈਂਟ ਬੇਨਤੀ — ₹{{fee}}",
    selectDateTimeError: "ਕਿਰਪਾ ਕਰਕੇ ਤਾਰੀਖ ਅਤੇ ਸਮਾਂ ਚੁਣੋ",
    slotBookedError: "ਇਹ ਸਲਾਟ ਪਹਿਲਾਂ ਹੀ ਬੁੱਕ ਹੈ",
    duplicateApptError: "ਇਸ ਸਮੇਂ ਤੁਹਾਡੀ ਪਹਿਲਾਂ ਹੀ ਇੱਕ ਅਪਾਇੰਟਮੈਂਟ ਹੈ",
    bookFailError: "ਅਪਾਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    specializations: {
      all: "ਸਾਰੇ",
      generalPhysician: "ਜਨਰਲ ਫਿਜ਼ੀਸ਼ੀਅਨ",
      cardiologist: "ਦਿਲ ਦੇ ਰੋਗਾਂ ਦਾ ਮਾਹਰ",
      dermatologist: "ਚਮੜੀ ਰੋਗਾਂ ਦਾ ਮਾਹਰ",
      neurologist: "ਨਿਊਰੋਲੋਜਿਸਟ",
      orthopedic: "ਹੱਡੀਆਂ ਦੇ ਰੋਗਾਂ ਦਾ ਮਾਹਰ",
      pediatrician: "ਬੱਚਿਆਂ ਦਾ ਡਾਕਟਰ",
      psychiatrist: "ਮਾਨਸਿਕ ਰੋਗਾਂ ਦਾ ਮਾਹਰ",
      ent: "ਈਐਨਟੀ"
    }
  }
};

const files = fs.readdirSync(LOCALES_DIR).filter(f => f.endsWith('.json'));

for (const file of files) {
  const lang = file.replace('.json', '');
  if (!DOCTORS_NS[lang]) {
    console.log(`⚠️  Skipped ${file} — no translation prepared for "${lang}"`);
    continue;
  }
  const filePath = path.join(LOCALES_DIR, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  if (data.doctors) {
    console.log(`⏭  ${file}: "doctors" namespace already exists — skipped (delete it first if you want to re-merge)`);
    continue;
  }

  data.doctors = DOCTORS_NS[lang];
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`✅ ${file}: added "doctors" namespace`);
}

console.log('\nDone. Run check_i18n_keys.js again to confirm all 10 files still match.');