// add_aichat_keys.js
// Adds the `aiChat` namespace to all 10 locale files.
// Scope: static UI chrome only (header, labels, placeholders, greeting,
// disclaimer, generic error fallback). The live chat conversation itself
// is generated by Gemini and follows the user's language automatically —
// intentionally left untranslated.
// Run with: node add_aichat_keys.js
// (ES module syntax — package.json has "type": "module")

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const LOCALES_DIR = path.join(__dirname, 'src', 'i18n', 'locales')

const LANGS = ['en', 'hi', 'mr', 'ta', 'te', 'kn', 'bn', 'ml', 'gu', 'pa']

const newKeys = {
  en: {
    aiChat: {
      header: {
        title: "Niraamo AI",
        subtitle: "Powered by Gemini · Ask about any medicine"
      },
      medicineInput: {
        label: "Medicine(s):",
        placeholder: "e.g. Paracetamol, Ibuprofen (optional)"
      },
      greeting: "Hello! I'm Niraamo AI 🤖 Ask me anything about medicines — side effects, dosage, interactions, pregnancy safety, and more!",
      inputPlaceholder: "Ask about side effects, dosage, interactions...",
      send: "Send",
      disclaimer: "Niraamo AI is for informational purposes only. Always consult a doctor.",
      errorFallback: "Something went wrong. Please try again."
    }
  },
  hi: {
    aiChat: {
      header: {
        title: "मेडीइन्फो एआई",
        subtitle: "Gemini द्वारा संचालित · किसी भी दवा के बारे में पूछें"
      },
      medicineInput: {
        label: "दवा(एं):",
        placeholder: "जैसे Paracetamol, Ibuprofen (वैकल्पिक)"
      },
      greeting: "नमस्ते! मैं मेडीइन्फो एआई हूँ 🤖 दवाओं के बारे में मुझसे कुछ भी पूछें — साइड इफ़ेक्ट, खुराक, इंटरैक्शन, गर्भावस्था में सुरक्षा, और भी बहुत कुछ!",
      inputPlaceholder: "साइड इफ़ेक्ट, खुराक, इंटरैक्शन के बारे में पूछें...",
      send: "भेजें",
      disclaimer: "मेडीइन्फो एआई केवल सूचना के उद्देश्य से है। हमेशा डॉक्टर से सलाह लें।",
      errorFallback: "कुछ गलत हो गया। कृपया फिर से प्रयास करें।"
    }
  },
  mr: {
    aiChat: {
      header: {
        title: "मेडीइन्फो एआई",
        subtitle: "Gemini द्वारा समर्थित · कोणत्याही औषधाबद्दल विचारा"
      },
      medicineInput: {
        label: "औषध(े):",
        placeholder: "उदा. Paracetamol, Ibuprofen (पर्यायी)"
      },
      greeting: "नमस्कार! मी मेडीइन्फो एआई आहे 🤖 औषधांबद्दल काहीही विचारा — दुष्परिणाम, मात्रा, परस्परसंवाद, गर्भधारणेतील सुरक्षितता आणि बरेच काही!",
      inputPlaceholder: "दुष्परिणाम, मात्रा, परस्परसंवादाबद्दल विचारा...",
      send: "पाठवा",
      disclaimer: "मेडीइन्फो एआई केवळ माहितीच्या उद्देशाने आहे. नेहमी डॉक्टरांचा सल्ला घ्या.",
      errorFallback: "काहीतरी चुकले. कृपया पुन्हा प्रयत्न करा."
    }
  },
  ta: {
    aiChat: {
      header: {
        title: "மெடிஇன்ஃபோ AI",
        subtitle: "Gemini மூலம் இயக்கப்படுகிறது · எந்த மருந்தைப் பற்றியும் கேளுங்கள்"
      },
      medicineInput: {
        label: "மருந்து(கள்):",
        placeholder: "எ.கா. Paracetamol, Ibuprofen (விருப்பத்திற்கு)"
      },
      greeting: "வணக்கம்! நான் மெடிஇன்ஃபோ AI 🤖 மருந்துகள் பற்றி எதையும் என்னிடம் கேளுங்கள் — பக்க விளைவுகள், அளவு, தொடர்வினைகள், கர்ப்ப பாதுகாப்பு மற்றும் இன்னும் பல!",
      inputPlaceholder: "பக்க விளைவுகள், அளவு, தொடர்வினைகள் பற்றி கேளுங்கள்...",
      send: "அனுப்பு",
      disclaimer: "மெடிஇன்ஃபோ AI தகவல் நோக்கங்களுக்காக மட்டுமே. எப்போதும் மருத்துவரை அணுகவும்.",
      errorFallback: "ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்."
    }
  },
  te: {
    aiChat: {
      header: {
        title: "మెడిఇన్ఫో AI",
        subtitle: "Gemini ద్వారా శక్తిని పొందింది · ఏ మందు గురించి అయినా అడగండి"
      },
      medicineInput: {
        label: "మందు(లు):",
        placeholder: "ఉదా. Paracetamol, Ibuprofen (ఐచ్ఛికం)"
      },
      greeting: "నమస్తే! నేను మెడిఇన్ఫో AI 🤖 మందుల గురించి ఏదైనా అడగండి — దుష్ప్రభావాలు, మోతాదు, ఇంటరాక్షన్లు, గర్భధారణ సురక్షితత మరియు మరిన్ని!",
      inputPlaceholder: "దుష్ప్రభావాలు, మోతాదు, ఇంటరాక్షన్ల గురించి అడగండి...",
      send: "పంపండి",
      disclaimer: "మెడిఇన్ఫో AI కేవలం సమాచార ప్రయోజనాల కోసం మాత్రమే. ఎల్లప్పుడూ వైద్యుడిని సంప్రదించండి.",
      errorFallback: "ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి."
    }
  },
  kn: {
    aiChat: {
      header: {
        title: "ಮೆಡಿಇನ್ಫೋ AI",
        subtitle: "Gemini ನಿಂದ ಚಾಲಿತ · ಯಾವುದೇ ಔಷಧದ ಬಗ್ಗೆ ಕೇಳಿ"
      },
      medicineInput: {
        label: "ಔಷಧ(ಗಳು):",
        placeholder: "ಉದಾ. Paracetamol, Ibuprofen (ಆಯ್ಕಿಕ)"
      },
      greeting: "ನಮಸ್ತೆ! ನಾನು ಮೆಡಿಇನ್ಫೋ AI 🤖 ಔಷಧಗಳ ಬಗ್ಗೆ ಏನು ಬೇಕಾದರೂ ಕೇಳಿ — ಅಡ್ಡಪರಿಣಾಮಗಳು, ಡೋಸೇಜ್, ಸಂವಾದಗಳು, ಗರ್ಭಧಾರಣೆ ಸುರಕ್ಷತೆ ಮತ್ತು ಇನ್ನೂ ಹೆಚ್ಚು!",
      inputPlaceholder: "ಅಡ್ಡಪರಿಣಾಮಗಳು, ಡೋಸೇಜ್, ಸಂವಾದಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
      send: "ಕಳುಹಿಸಿ",
      disclaimer: "ಮೆಡಿಇನ್ಫೋ AI ಕೇವಲ ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ. ಯಾವಾಗಲೂ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
      errorFallback: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."
    }
  },
  bn: {
    aiChat: {
      header: {
        title: "মেডিইনফো AI",
        subtitle: "Gemini দ্বারা চালিত · কোনো ওষুধ সম্পর্কে জিজ্ঞাসা করুন"
      },
      medicineInput: {
        label: "ওষুধ(গুলি):",
        placeholder: "যেমন Paracetamol, Ibuprofen (ঐচ্ছিক)"
      },
      greeting: "নমস্কার! আমি মেডিইনফো AI 🤖 ওষুধ সম্পর্কে যা কিছু জিজ্ঞাসা করুন — পার্শ্বপ্রতিক্রিয়া, ডোজ, মিথস্ক্রিয়া, গর্ভাবস্থার সুরক্ষা এবং আরও অনেক কিছু!",
      inputPlaceholder: "পার্শ্বপ্রতিক্রিয়া, ডোজ, মিথস্ক্রিয়া সম্পর্কে জিজ্ঞাসা করুন...",
      send: "পাঠান",
      disclaimer: "মেডিইনফো AI শুধুমাত্র তথ্যের উদ্দেশ্যে। সর্বদা একজন ডাক্তারের পরামর্শ নিন।",
      errorFallback: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।"
    }
  },
  ml: {
    aiChat: {
      header: {
        title: "മെഡിഇൻഫോ AI",
        subtitle: "Gemini പ്രവർത്തിപ്പിക്കുന്നു · ഏത് മരുന്നിനെക്കുറിച്ചും ചോദിക്കുക"
      },
      medicineInput: {
        label: "മരുന്ന്(ങ്ങൾ):",
        placeholder: "ഉദാ. Paracetamol, Ibuprofen (ഓപ്ഷണൽ)"
      },
      greeting: "നമസ്കാരം! ഞാൻ മെഡിഇൻഫോ AI 🤖 മരുന്നുകളെക്കുറിച്ച് എന്തും എന്നോട് ചോദിക്കുക — പാർശ്വഫലങ്ങൾ, ഡോസേജ്, ഇടപെടലുകൾ, ഗർഭധാരണ സുരക്ഷ എന്നിവയും അതിലേറെയും!",
      inputPlaceholder: "പാർശ്വഫലങ്ങൾ, ഡോസേജ്, ഇടപെടലുകളെക്കുറിച്ച് ചോദിക്കുക...",
      send: "അയക്കുക",
      disclaimer: "മെഡിഇൻഫോ AI വിവര ലക്ഷ്യങ്ങൾക്ക് മാത്രമാണ്. എപ്പോഴും ഒരു ഡോക്ടറെ സമീപിക്കുക.",
      errorFallback: "എന്തോ കുഴപ്പം സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക."
    }
  },
  gu: {
    aiChat: {
      header: {
        title: "મેડીઇન્ફો AI",
        subtitle: "Gemini દ્વારા સંચાલિત · કોઈપણ દવા વિશે પૂછો"
      },
      medicineInput: {
        label: "દવા(ઓ):",
        placeholder: "દા.ત. Paracetamol, Ibuprofen (વૈકલ્પિક)"
      },
      greeting: "નમસ્તે! હું મેડીઇન્ફો AI છું 🤖 દવાઓ વિશે કંઈપણ પૂછો — આડઅસરો, માત્રા, ક્રિયાપ્રતિક્રિયાઓ, ગર્ભાવસ્થા સલામતી અને ઘણું બધું!",
      inputPlaceholder: "આડઅસરો, માત્રા, ક્રિયાપ્રતિક્રિયાઓ વિશે પૂછો...",
      send: "મોકલો",
      disclaimer: "મેડીઇન્ફો AI માત્ર માહિતીના હેતુ માટે છે. હંમેશા ડૉક્ટરની સલાહ લો.",
      errorFallback: "કંઈક ખોટું થયું. કૃપા કરી ફરી પ્રયાસ કરો."
    }
  },
  pa: {
    aiChat: {
      header: {
        title: "ਮੇਡੀਇਨਫੋ AI",
        subtitle: "Gemini ਦੁਆਰਾ ਸੰਚਾਲਿਤ · ਕਿਸੇ ਵੀ ਦਵਾਈ ਬਾਰੇ ਪੁੱਛੋ"
      },
      medicineInput: {
        label: "ਦਵਾਈ(ਆਂ):",
        placeholder: "ਜਿਵੇਂ Paracetamol, Ibuprofen (ਚੋਣਵਾਂ)"
      },
      greeting: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਮੇਡੀਇਨਫੋ AI ਹਾਂ 🤖 ਦਵਾਈਆਂ ਬਾਰੇ ਮੈਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ — ਮਾੜੇ ਪ੍ਰਭਾਵ, ਖੁਰਾਕ, ਪਰਸਪਰ ਪ੍ਰਭਾਵ, ਗਰਭ ਅਵਸਥਾ ਸੁਰੱਖਿਆ ਅਤੇ ਹੋਰ ਵੀ ਬਹੁਤ ਕੁਝ!",
      inputPlaceholder: "ਮਾੜੇ ਪ੍ਰਭਾਵ, ਖੁਰਾਕ, ਪਰਸਪਰ ਪ੍ਰਭਾਵ ਬਾਰੇ ਪੁੱਛੋ...",
      send: "ਭੇਜੋ",
      disclaimer: "ਮੇਡੀਇਨਫੋ AI ਸਿਰਫ਼ ਜਾਣਕਾਰੀ ਦੇ ਉਦੇਸ਼ਾਂ ਲਈ ਹੈ। ਹਮੇਸ਼ਾ ਡਾਕਟਰ ਦੀ ਸਲਾਹ ਲਓ।",
      errorFallback: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।"
    }
  }
}

function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (
      source[key] &&
      typeof source[key] === 'object' &&
      !Array.isArray(source[key])
    ) {
      if (!target[key] || typeof target[key] !== 'object') {
        target[key] = {}
      }
      deepMerge(target[key], source[key])
    } else {
      target[key] = source[key]
    }
  }
  return target
}

let successCount = 0
let failCount = 0

for (const lang of LANGS) {
  const filePath = path.join(LOCALES_DIR, `${lang}.json`)
  try {
    const raw = fs.readFileSync(filePath, 'utf-8')
    const json = JSON.parse(raw)
    deepMerge(json, newKeys[lang])
    fs.writeFileSync(filePath, JSON.stringify(json, null, 2) + '\n', 'utf-8')
    console.log(`✔ Updated ${lang}.json`)
    successCount++
  } catch (err) {
    console.error(`✘ Failed on ${lang}.json:`, err.message)
    failCount++
  }
}

console.log(`\nDone. ${successCount} updated, ${failCount} failed.`)